//! Software microphone enhancement through PipeWire.
//!
//! On Windows, Synapse's "mic enhancement" (ambient noise reduction, volume
//! normalization, voice clarity) runs in software, not in the headset. The
//! Linux counterpart is PipeWire's echo-cancel module with the WebRTC audio
//! processing library: noise suppression, automatic gain control and a
//! high-pass filter. It publishes a new virtual source ("clean mic") fed from
//! the headset microphone.
//!
//! The filter runs as its own PipeWire client process managed by a systemd
//! user unit, like PipeWire's own `filter-chain.service`, so enabling or
//! disabling it never restarts the user's audio server.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use serde::Serialize;

pub const SERVICE: &str = "synapse-linux-mic.service";
pub const CLEAN_NODE: &str = "synapse_linux.mic_clean";
const CAPTURE_NODE: &str = "synapse_linux.mic_capture";
const REFERENCE_NODE: &str = "synapse_linux.mic_reference";

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct AudioNode {
    pub name: String,
    pub description: String,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize)]
pub struct MicCleanStatus {
    /// The WebRTC processing plugin is installed.
    pub plugin_available: bool,
    /// Starts together with PipeWire.
    pub enabled: bool,
    /// Running right now.
    pub active: bool,
    /// Microphone the filter reads from (from our generated config).
    pub target: Option<String>,
    /// The clean source is the system default input.
    pub is_default: bool,
}

fn spa_plugin_dirs() -> Vec<PathBuf> {
    let mut dirs: Vec<PathBuf> = std::env::var_os("SPA_PLUGIN_DIR")
        .map(|v| std::env::split_paths(&v).collect())
        .unwrap_or_default();
    for dir in [
        "/usr/lib/spa-0.2",
        "/usr/lib64/spa-0.2",
        "/usr/lib/x86_64-linux-gnu/spa-0.2",
        "/usr/lib/aarch64-linux-gnu/spa-0.2",
        "/usr/local/lib/spa-0.2",
    ] {
        dirs.push(PathBuf::from(dir));
    }
    dirs
}

pub fn plugin_available() -> bool {
    spa_plugin_dirs()
        .iter()
        .any(|dir| dir.join("aec/libspa-aec-webrtc.so").exists())
}

fn app_config_dir() -> Option<PathBuf> {
    dirs::config_dir().map(|dir| dir.join("synapse-linux"))
}

pub fn filter_config_path() -> Option<PathBuf> {
    app_config_dir().map(|dir| dir.join("pipewire").join("mic-clean.conf"))
}

pub fn unit_path() -> Option<PathBuf> {
    dirs::config_dir().map(|dir| dir.join("systemd").join("user").join(SERVICE))
}

/// Quote a string for PipeWire's SPA-JSON config syntax.
fn spa_quote(text: &str) -> String {
    let mut out = String::with_capacity(text.len() + 2);
    out.push('"');
    for c in text.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' | '\r' => out.push(' '),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// Configuration for a standalone `pipewire -c` process running the filter.
pub fn render_filter_config(target: &str, description: &str) -> String {
    format!(
        r#"# Generated by Synapse for Linux. Regenerated when the feature is toggled.
# Clean microphone: WebRTC noise suppression + automatic gain + high-pass filter.
context.properties = {{
    log.level = 0
}}
context.spa-libs = {{
    audio.convert.* = audioconvert/libspa-audioconvert
    support.*       = support/libspa-support
}}
context.modules = [
    {{ name = libpipewire-module-rt
        args = {{ }}
        flags = [ ifexists nofail ]
    }}
    {{ name = libpipewire-module-protocol-native }}
    {{ name = libpipewire-module-client-node }}
    {{ name = libpipewire-module-adapter }}
    {{ name = libpipewire-module-echo-cancel
        args = {{
            library.name   = aec/libspa-aec-webrtc
            # Use the monitor of the default output as echo reference
            # instead of creating an extra output device.
            monitor.mode   = true
            audio.channels = 1
            audio.position = [ MONO ]
            aec.args = {{
                webrtc.noise_suppression     = true
                webrtc.gain_control          = true
                webrtc.high_pass_filter      = true
                webrtc.voice_detection       = true
                webrtc.transient_suppression = false
            }}
            capture.props = {{
                node.name          = {capture}
                node.description   = {capture_desc}
                target.object      = {target}
                node.passive       = true
                # Never fall back to another microphone (e.g. the clean one itself).
                node.dont-fallback = true
            }}
            source.props = {{
                node.name        = {clean}
                node.description = {description}
                media.class      = Audio/Source
            }}
            # Stream reading the default output as echo reference.
            sink.props = {{
                node.name        = {reference}
                node.description = {reference_desc}
            }}
        }}
    }}
]
"#,
        capture = spa_quote(CAPTURE_NODE),
        capture_desc = spa_quote(&format!("{description} (input)")),
        target = spa_quote(target),
        clean = spa_quote(CLEAN_NODE),
        description = spa_quote(description),
        reference = spa_quote(REFERENCE_NODE),
        reference_desc = spa_quote(&format!("{description} (echo reference)")),
    )
}

pub fn render_unit(pipewire: &Path, config: &Path) -> String {
    format!(
        "# Generated by Synapse for Linux.\n\
         [Unit]\n\
         Description=Synapse for Linux clean microphone (PipeWire noise suppression)\n\
         After=pipewire.service pipewire-session-manager.service\n\
         BindsTo=pipewire.service\n\
         \n\
         [Service]\n\
         Type=simple\n\
         ExecStart=\"{}\" -c \"{}\"\n\
         Restart=on-failure\n\
         RestartSec=2\n\
         Slice=session.slice\n\
         \n\
         [Install]\n\
         WantedBy=default.target\n",
        pipewire.display(),
        config.display()
    )
}

/// Read back the target microphone from a generated config.
fn parse_target(config: &str) -> Option<String> {
    config.lines().find_map(|line| {
        let rest = line
            .trim()
            .strip_prefix("target.object")?
            .trim_start()
            .strip_prefix('=')?
            .trim();
        let inner = rest.strip_prefix('"')?.strip_suffix('"')?;
        Some(inner.replace("\\\"", "\"").replace("\\\\", "\\"))
    })
}

fn run(program: &str, args: &[&str]) -> Result<String, String> {
    let output = Command::new(program)
        .args(args)
        .output()
        .map_err(|err| format!("cannot run {program}: {err}"))?;
    if output.status.success() {
        Ok(String::from_utf8_lossy(&output.stdout).trim().to_string())
    } else {
        let stderr = String::from_utf8_lossy(&output.stderr).trim().to_string();
        Err(format!("{program} {}: {stderr}", args.join(" ")))
    }
}

fn find_in_path(program: &str) -> Option<PathBuf> {
    std::env::var_os("PATH")
        .into_iter()
        .flat_map(|paths| std::env::split_paths(&paths).collect::<Vec<_>>())
        .map(|dir| dir.join(program))
        .find(|path| path.is_file())
}

/// All PipeWire audio sources (via `pw-dump`).
pub fn list_sources() -> Result<Vec<AudioNode>, String> {
    let dump = run("pw-dump", &[])?;
    parse_sources(&dump)
}

fn parse_sources(dump: &str) -> Result<Vec<AudioNode>, String> {
    let objects: Vec<serde_json::Value> = serde_json::from_str(dump).map_err(|err| format!("pw-dump: {err}"))?;
    Ok(objects
        .iter()
        .filter(|o| o["type"] == "PipeWire:Interface:Node")
        .filter_map(|o| {
            let props = &o["info"]["props"];
            if props["media.class"] != "Audio/Source" {
                return None;
            }
            let name = props["node.name"].as_str()?.to_string();
            let description = props["node.description"].as_str().unwrap_or(&name).to_string();
            Some(AudioNode { name, description })
        })
        .collect())
}

/// The headset microphone (hardware source of a Razer USB audio device).
pub fn find_razer_source() -> Option<AudioNode> {
    pick_razer_source(list_sources().ok()?)
}

fn pick_razer_source(sources: Vec<AudioNode>) -> Option<AudioNode> {
    sources.into_iter().find(|node| {
        let text = format!("{} {}", node.name, node.description).to_lowercase();
        node.name != CLEAN_NODE
            && node.name.starts_with("alsa_input.")
            && (text.contains("razer") || text.contains("blackshark"))
    })
}

pub fn default_source() -> Option<String> {
    run("pactl", &["get-default-source"]).ok().filter(|s| !s.is_empty())
}

pub fn set_default_source(name: &str) -> Result<(), String> {
    run("pactl", &["set-default-source", name]).map(drop)
}

fn systemctl(args: &[&str]) -> Result<String, String> {
    let mut all = vec!["--user"];
    all.extend_from_slice(args);
    run("systemctl", &all)
}

pub fn status() -> MicCleanStatus {
    let target = filter_config_path()
        .and_then(|path| fs::read_to_string(path).ok())
        .and_then(|text| parse_target(&text));
    let enabled = systemctl(&["is-enabled", SERVICE]).is_ok_and(|s| s == "enabled");
    let active = systemctl(&["is-active", SERVICE]).is_ok_and(|s| s == "active");
    MicCleanStatus {
        plugin_available: plugin_available(),
        enabled,
        active,
        target,
        is_default: active && default_source().as_deref() == Some(CLEAN_NODE),
    }
}

/// Create (or update) the clean microphone for `target` and start it.
pub fn enable(target: &str, description: &str) -> Result<(), String> {
    if !plugin_available() {
        return Err("the PipeWire WebRTC plugin (aec/libspa-aec-webrtc.so) is not installed".into());
    }
    let pipewire = find_in_path("pipewire").ok_or("the pipewire program was not found")?;
    let config_path = filter_config_path().ok_or("no config directory")?;
    let unit_path = unit_path().ok_or("no config directory")?;
    for path in [&config_path, &unit_path] {
        if let Some(dir) = path.parent() {
            fs::create_dir_all(dir).map_err(|err| format!("cannot create {}: {err}", dir.display()))?;
        }
    }
    fs::write(&config_path, render_filter_config(target, description))
        .map_err(|err| format!("cannot write {}: {err}", config_path.display()))?;
    fs::write(&unit_path, render_unit(&pipewire, &config_path))
        .map_err(|err| format!("cannot write {}: {err}", unit_path.display()))?;
    systemctl(&["daemon-reload"])?;
    systemctl(&["enable", SERVICE])?;
    // Restart so an updated config is picked up when it was already running.
    systemctl(&["restart", SERVICE])?;
    Ok(())
}

/// Stop and remove the clean microphone.
pub fn disable() -> Result<(), String> {
    let status = status();
    if status.is_default {
        // Hand the default input back to the real microphone first.
        if let Some(target) = status.target.as_deref() {
            let _ = set_default_source(target);
        }
    }
    let unit_exists = unit_path().is_some_and(|p| p.exists());
    if unit_exists {
        systemctl(&["disable", "--now", SERVICE])?;
    }
    for path in [unit_path(), filter_config_path()].into_iter().flatten() {
        if path.exists() {
            fs::remove_file(&path).map_err(|err| format!("cannot remove {}: {err}", path.display()))?;
        }
    }
    // Drop our (now empty) pipewire/ config folder; fails harmlessly if not empty.
    if let Some(dir) = filter_config_path().as_deref().and_then(Path::parent) {
        let _ = fs::remove_dir(dir);
    }
    if unit_exists {
        systemctl(&["daemon-reload"])?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn config_contains_target_and_roundtrips_it() {
        let target = "alsa_input.usb-MediaTek_Inc_Razer_BlackShark_V2_HS_2.4_0000000000000000-00.mono-fallback";
        let text = render_filter_config(target, "Razer Mic (Clean)");
        assert!(text.contains("library.name   = aec/libspa-aec-webrtc"));
        assert!(text.contains("node.dont-fallback = true"));
        assert!(text.contains(&format!("\"{target}\"")));
        assert_eq!(parse_target(&text).as_deref(), Some(target));
        // Braces must balance or PipeWire refuses the file.
        assert_eq!(text.matches('{').count(), text.matches('}').count());
        assert_eq!(text.matches('[').count(), text.matches(']').count());
    }

    #[test]
    fn quoting_escapes_specials() {
        assert_eq!(spa_quote(r#"a "b" \c"#), r#""a \"b\" \\c""#);
        let text = render_filter_config(r#"we"ird"#, "x");
        assert_eq!(parse_target(&text).as_deref(), Some(r#"we"ird"#));
    }

    #[test]
    fn unit_runs_pipewire_with_config() {
        let unit = render_unit(
            Path::new("/usr/bin/pipewire"),
            Path::new("/home/u/.config/synapse-linux/pipewire/mic-clean.conf"),
        );
        assert!(
            unit.contains(
                "ExecStart=\"/usr/bin/pipewire\" -c \"/home/u/.config/synapse-linux/pipewire/mic-clean.conf\""
            )
        );
        assert!(unit.contains("BindsTo=pipewire.service"));
        assert!(unit.contains("WantedBy=default.target"));
    }

    #[test]
    fn finds_razer_source_in_pw_dump() {
        let dump = r#"[
          {"id": 1, "type": "PipeWire:Interface:Node", "info": {"props": {"media.class": "Audio/Sink", "node.name": "alsa_output.usb-MediaTek_Inc_Razer_BlackShark_V2_HS_2.4-00.analog-stereo"}}},
          {"id": 2, "type": "PipeWire:Interface:Node", "info": {"props": {"media.class": "Audio/Source", "node.name": "alsa_input.pci-0000_00_1f.3.analog-stereo", "node.description": "Built-in Audio"}}},
          {"id": 3, "type": "PipeWire:Interface:Node", "info": {"props": {"media.class": "Audio/Source", "node.name": "synapse_linux.mic_clean", "node.description": "Razer Mic (Clean)"}}},
          {"id": 4, "type": "PipeWire:Interface:Node", "info": {"props": {"media.class": "Audio/Source", "node.name": "alsa_input.usb-MediaTek_Inc_Razer_BlackShark_V2_HS_2.4-00.mono-fallback", "node.description": "Razer BlackShark V2 HS 2.4 Mono"}}},
          {"id": 5, "type": "PipeWire:Interface:Port", "info": {"props": {}}}
        ]"#;
        let sources = parse_sources(dump).unwrap();
        assert_eq!(sources.len(), 3);
        let razer = pick_razer_source(sources).unwrap();
        assert_eq!(
            razer.name,
            "alsa_input.usb-MediaTek_Inc_Razer_BlackShark_V2_HS_2.4-00.mono-fallback"
        );
        assert!(parse_sources("not json").is_err());
    }
}
